export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
// export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
// export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_FACILITY_TYPE_COMMITTEE = 'GET_FACILITY_TYPE_COMMITTEE'

export const GET_ROOMS = 'GET_ROOMS'
export const FETCH_ROOMS_ERROR = 'FETCH_ROOMS_ERROR'
export const CLEAR_ROOMS = 'CLEAR_ROOMS'
export const FILTER_ERROR = 'FILTER_ERROR'

export const ADD_NEW_EVENT = 'ADD_NEW_EVENT'
export const GET_USER_EVENTS = 'GET_USER_EVENTS'
export const USER_EVENTS_ERROR = 'USER_EVENTS_ERROR'
export const CLEAR_EVENT_ADDED = 'CLEAR_EVENT_ADDED'
export const EVENT_ERROR = 'EVENT_ERROR'
export const SELECT_EVENT = 'SELECT_EVENT'
export const REMOVE_SELECTED_EVENT = 'REMOVE_SELECTED_EVENT'

export const GET_VACANT_SLOTS = 'GET_VACANT_SLOTS'
export const TIME_SLOT_ERROR = 'TIME_SLOT_ERROR'
export const ADD_TIME_SLOT = 'ADD_TIME_SLOT'
export const REMOVE_TIME_SLOT = 'REMOVE_TIME_SLOT'
export const CLEAR_TIME_SLOT = 'CLEAR_TIME_SLOT'

export const GET_TIMETABLE = 'GET_TIMETABLE'
export const TIMETABLE_ERROR = 'TIMETABLE_ERROR'

export const GET_UNREAD_REQUESTS = 'GET_UNREAD_REQUESTS'
export const GET_READ_REQUESTS = 'GET_READ_REQUESTS'
export const ADD_NEW_REQUEST = 'ADD_NEW_REQUEST'
export const CLEAR_ADDED_REQUEST = 'CLEAR_ADDED_REQUEST'
export const REQUESTS_ERROR = 'REQUESTS_ERROR'